### PR TITLE
made some changes to the mediacard

### PR DESCRIPTION
**Pull request by fanlimgames**
**hello i have made some changes to the mediacard to  i think this makes it big difference **

### CODE REVIEW

**Comment by fanlimgames** [comment]
here is how it looks now https://sussy-code.vercel.app

**Comment by fanlimgames** [comment]
i just cleane upi your index,html and other changes i think you are going to like but yeah sure you can fix it

**Comment by fanlimgames** [comment]
also if you are intersted we could work on this together to improve the website if you want to of course

**Comment by fanlimgames** [comment]
added a new provider also this one has no ads

**Comment by fanlimgames** [comment]
@ambr0sial this should do it enjoy the new changes

**Comment by ambr0sial** [comment]
you're going too far. remember this is my repo, so please dont change links like ko-fi and all, same with the cname. im not at home right now but when i am i'll probably cherry-pick the commits.

> also if you are intersted we could work on this together to improve the website if you want to of course

im not interested into fully working with other people on the website, but pull requests are still available!

**Pull request closed without merging**
